read_arch WorkSpace/public/Arch/fpga.lib WorkSpace/public/Arch/fpga.scl WorkSpace/public/Arch/fpga.clk
report_arch

read_design WorkSpace/public/Benchmark/public_release/case_10.nodes WorkSpace/public/Benchmark/public_release/case_10.nets WorkSpace/public/Benchmark/public_release/case_10.timing

SA
FM

generateResult /home/pc/aibot/wbx/EDAElite/WorkSpace/public/Test/Result/case_10.nodes.out

exit
